filters:
  include_keywords: []
  include_tickers:  []

categories:
  macro: ["inflation","CPI","PCE","jobs","employment","payrolls","unemployment","ISM","PMI","GDP"]
  rates: ["rate","rates","yield","Treasury","bond","auction","Fed","FOMC","dot plot","Powell"]
  fx: ["dollar","greenback","EUR","JPY","CNY","yuan","FX","forex"]
  crypto: ["bitcoin","BTC","ETH","crypto"]
  energy: ["oil","WTI","Brent","OPEC","gas","energy"]
  earnings: ["earnings","EPS","revenue","guidance","outlook","beat","miss"]
  tech: ["AI","chip","semiconductor","GPU","datacenter","cloud","software","cybersecurity","TSMC","NVIDIA","NVDA"]
  geopolitics: ["sanction","tariff","ban","trade","geopolit","war","conflict"]

sources:
  - name: yahoo_finance
    enabled: true
    type: rss
    url: https://finance.yahoo.com/news/rssindex

  - name: reuters_markets_via_gnews
    enabled: true
    type: rss
    url: "https://news.google.com/rss/search?q=site:reuters.com+markets&hl=en-US&gl=US&ceid=US:en"

  - name: reuters_business_via_gnews
    enabled: true
    type: rss
    url: "https://news.google.com/rss/search?q=site:reuters.com+business&hl=en-US&gl=US&ceid=US:en"

  - name: cnbc_markets
    enabled: true
    type: rss
    url: https://www.cnbc.com/id/100003114/device/rss/rss.html

  - name: bloomberg_via_gnews
    enabled: true
    type: rss
    url: "https://news.google.com/rss/search?q=site:bloomberg.com+(markets+OR+stocks+OR+earnings)&hl=en-US&gl=US&ceid=US:en"

  - name: marketwatch_via_gnews
    enabled: true
    type: rss
    url: "https://news.google.com/rss/search?q=site:marketwatch.com+(markets+OR+stocks+OR+earnings)&hl=en-US&gl=US&ceid=US:en"

  - name: barrons_via_gnews
    enabled: true
    type: rss
    url: "https://news.google.com/rss/search?q=site:barrons.com+(markets+OR+stocks+OR+earnings)&hl=en-US&gl=US&ceid=US:en"

  - name: ft_via_gnews
    enabled: true
    type: rss
    url: "https://news.google.com/rss/search?q=site:ft.com+(markets+OR+stocks+OR+earnings)&hl=en-US&gl=US&ceid=US:en"

  - name: seekingalpha_via_gnews
    enabled: true
    type: rss
    url: "https://news.google.com/rss/search?q=site:seekingalpha.com+(markets+OR+stocks+OR+earnings)&hl=en-US&gl=US&ceid=US:en"

  - name: nasdaq_via_gnews
    enabled: true
    type: rss
    url: "https://news.google.com/rss/search?q=site:nasdaq.com+(news+OR+earnings+OR+markets)&hl=en-US&gl=US&ceid=US:en"

  - name: investing_via_gnews
    enabled: true
    type: rss
    url: "https://news.google.com/rss/search?q=site:investing.com+(news+OR+markets+OR+stocks)&hl=en-US&gl=US&ceid=US:en"

  - name: wsj_via_gnews
    enabled: true
    type: rss
    url: "https://news.google.com/rss/search?q=site:wsj.com+(markets+OR+stocks+OR+earnings)&hl=en-US&gl=US&ceid=US:en"

  # Dynamic sources disabled for stability
  - name: financialjuice
    enabled: false
    type: playwright
    url: https://www.financialjuice.com/home

  - name: jin10_flash
    enabled: false
    type: playwright
    url: https://www.jin10.com/flash
